/**
 * Small, client-safe descriptions for the playground's simulated mini-apps.
 * No credential, binding, or private workflow data belongs in this module.
 */
export const DEFAULT_SCENARIO_ID = "invoice";

export const PLAYGROUND_SCENARIOS = Object.freeze([
  Object.freeze({
    id: "invoice",
    brand: "Ledgerly",
    mark: "L",
    category: "Finance operations",
    tagline: "Calm control for company spend.",
    navItems: ["Overview", "Bills", "Approvals", "Vendors"],
    navActive: "Approvals",
    workspaceLabel: "Approval queue",
    pageTitle: "Good morning, Maya",
    description: "Review the next payment decision before it moves to your finance team.",
    metricLabel: "Awaiting approval",
    metricValue: "07",
    metricMeta: "2 due this week",
    secondaryMetricLabel: "This month",
    secondaryMetricValue: "$18.4k",
    secondaryMetricMeta: "approved spend",
    recordLabel: "Invoice #1042",
    recordValue: "$2,480.00",
    recordMeta: "Northstar Studio · Due in 14 days",
    recordStatus: "Awaiting review",
    recordDetail: "Brand system refresh · Net 30",
    workflowId: "ledgerly-invoice-1042",
    workflowType: "invoice_approval",
    recordId: "INV-1042",
    agentInstruction: "Read invoice INV-1042 and prepare the next safe review step. Do not approve or pay it.",
    webmcp: Object.freeze({
      statusToolName: "ledgerly_get_invoice_status",
      statusToolDescription: "Read the current status of Ledgerly invoice INV-1042 and the next safe review step.",
      consentToolName: "ledgerly_request_invoice_updates",
      consentToolDescription: "Ask the user to approve one future return to Ledgerly when invoice INV-1042 is ready for review.",
    }),
    userAction: "Review invoice",
    developerAction: "Mark invoice approved",
    developerResult: "Invoice approved",
    consentTitle: "Approve this invoice demo?",
    consentReason: "Allow Ledgerly to return when this invoice is ready for the next review.",
  }),
  Object.freeze({
    id: "pickup",
    brand: "Parcelly",
    mark: "P",
    category: "Commerce operations",
    tagline: "Good things, right on time.",
    navItems: ["Shop", "Orders", "Pickup", "Account"],
    navActive: "Orders",
    workspaceLabel: "Your orders",
    pageTitle: "A little update on the way",
    description: "Your local store is getting your order ready. We will keep the handoff simple.",
    metricLabel: "Order total",
    metricValue: "$86.00",
    metricMeta: "Paid with Visa · 4242",
    secondaryMetricLabel: "Pickup window",
    secondaryMetricValue: "Today",
    secondaryMetricMeta: "4:00–6:00 PM",
    recordLabel: "Order #7819",
    recordValue: "Ready soon",
    recordMeta: "Wireless keyboard · Store 04",
    recordStatus: "Preparing order",
    recordDetail: "Sand · Quantity 1",
    workflowId: "parcelly-order-7819",
    workflowType: "order_pickup",
    recordId: "ORDER-7819",
    agentInstruction: "Read order ORDER-7819 and prepare the next safe pickup step. Do not collect or cancel it.",
    webmcp: Object.freeze({
      statusToolName: "parcelly_get_order_status",
      statusToolDescription: "Read the current pickup status of Parcelly order ORDER-7819 and the next safe step.",
      consentToolName: "parcelly_request_order_updates",
      consentToolDescription: "Ask the user to approve one future return to Parcelly when order ORDER-7819 is ready for pickup.",
    }),
    userAction: "Get pickup updates",
    developerAction: "Mark order ready",
    developerResult: "Order ready for pickup",
    consentTitle: "Approve this order demo?",
    consentReason: "Allow Parcelly to return when this order is ready for pickup.",
  }),
  Object.freeze({
    id: "support",
    brand: "Kindline",
    mark: "K",
    category: "Customer support",
    tagline: "Every question deserves a human answer.",
    navItems: ["Inbox", "My tickets", "Help center", "Account"],
    navActive: "My tickets",
    workspaceLabel: "My support",
    pageTitle: "We are on it",
    description: "Your support conversation is in good hands. See the latest note from our team.",
    metricLabel: "Response time",
    metricValue: "12 min",
    metricMeta: "Average this week",
    secondaryMetricLabel: "Open tickets",
    secondaryMetricValue: "02",
    secondaryMetricMeta: "Both with a specialist",
    recordLabel: "Ticket #3308",
    recordValue: "In progress",
    recordMeta: "Login issue · Priority normal",
    recordStatus: "Agent replied",
    recordDetail: "Last updated 8 minutes ago",
    workflowId: "kindline-ticket-3308",
    workflowType: "support_resolution",
    recordId: "TICKET-3308",
    agentInstruction: "Read ticket TICKET-3308 and prepare the next safe support step. Do not close or send a reply.",
    webmcp: Object.freeze({
      statusToolName: "kindline_get_ticket_status",
      statusToolDescription: "Read the current status of Kindline ticket TICKET-3308 and the next safe support step.",
      consentToolName: "kindline_request_ticket_updates",
      consentToolDescription: "Ask the user to approve one future return to Kindline when ticket TICKET-3308 is resolved.",
    }),
    userAction: "Keep me posted",
    developerAction: "Mark ticket resolved",
    developerResult: "Ticket resolved",
    consentTitle: "Approve this support demo?",
    consentReason: "Allow Kindline to return when this support ticket is resolved.",
  }),
  Object.freeze({
    id: "proposal",
    brand: "Morrow",
    mark: "m.",
    category: "Creative studio",
    tagline: "Make good work easy to sign.",
    navItems: ["Projects", "Proposals", "Invoices", "Profile"],
    navActive: "Proposals",
    workspaceLabel: "Proposal desk",
    pageTitle: "A thoughtful next step",
    description: "Your proposal is almost there. Review the latest version before it goes live.",
    metricLabel: "Project value",
    metricValue: "$8,900",
    metricMeta: "Brand refresh · 6 weeks",
    secondaryMetricLabel: "Decision due",
    secondaryMetricValue: "Friday",
    secondaryMetricMeta: "Client review window",
    recordLabel: "Proposal #208",
    recordValue: "Awaiting reply",
    recordMeta: "Brand refresh · Morrow Studio",
    recordStatus: "Client reviewing",
    recordDetail: "Version 03 · Sent yesterday",
    workflowId: "morrow-proposal-208",
    workflowType: "proposal_review",
    recordId: "PROPOSAL-208",
    agentInstruction: "Read proposal PROPOSAL-208 and prepare the next safe client-review step. Do not accept or publish it.",
    webmcp: Object.freeze({
      statusToolName: "morrow_get_proposal_status",
      statusToolDescription: "Read the current status of Morrow proposal PROPOSAL-208 and the next safe client-review step.",
      consentToolName: "morrow_request_proposal_updates",
      consentToolDescription: "Ask the user to approve one future return to Morrow when proposal PROPOSAL-208 is accepted.",
    }),
    userAction: "Get proposal updates",
    developerAction: "Mark proposal accepted",
    developerResult: "Proposal accepted",
    consentTitle: "Approve this proposal demo?",
    consentReason: "Allow Morrow to return when this proposal is accepted.",
  }),
]);

export function getPlaygroundScenario(id) {
  return PLAYGROUND_SCENARIOS.find((scenario) => scenario.id === id) ?? null;
}

export function scenarioCanonicalPath(id) {
  return `/?scenario=${encodeURIComponent(id)}`;
}
